### ISSUE TITLE
Compile failure on Ubuntu 14.04 LTS with -DMYSQL_MAINTAINER_MODE=1

### ISSUE THREAD

**Issue by spetrunia** [MySQLOnRocksDB/mysql-5.6#23]
I'm trying to compile on Ubuntu 14.04 LTS (gcc version Ubuntu 4.8.2-19ubuntu1), using this line:

```
cmake . -DCMAKE_BUILD_TYPE=Debug -DWITH_SSL:STRING=system \
-DWITH_ZLIB:STRING=system -DMYSQL_MAINTAINER_MODE=1
```

and I'm getting two compile errors:

```
[ 30%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/dict/dict0mem.cc.o
/home/psergey/dev-git/mysql-5.6-rocksdb-fixcompile/storage/innobase/dict/dict0mem.cc: In function 'void dict_mem_index_add_field(dict_index_t*, const char*, ulint)':
/home/psergey/dev-git/mysql-5.6-rocksdb-fixcompile/storage/innobase/dict/dict0mem.cc:678:63: error: passing NULL to non-pointer argument 5 of 'void dict_mem_index_add_field(dict_index_t*, const char*, ulint, char**, uint, unsigned int)' [-Werror=conversion-null]
   dict_mem_index_add_field(index, name, prefix_len, 0, NULL, 0);
                                                               ^
cc1plus: all warnings being treated as errors
make[2]: *** [storage/innobase/CMakeFiles/innobase.dir/dict/dict0mem.cc.o] Error 1
make[2]: Target `storage/innobase/CMakeFiles/innobase.dir/build' not remade because of errors.
make[1]: *** [storage/innobase/CMakeFiles/innobase.dir/all] Error 2
```

and 

```
Scanning dependencies of target mysqlbinlog
[ 39%] Building CXX object client/CMakeFiles/mysqlbinlog.dir/mysqlbinlog.cc.o
/home/psergey/dev-git/mysql-5.6-rocksdb-fixcompile/client/mysqlbinlog.cc: In function 'Exit_status dump_remote_log_entries(PRINT_EVENT_INFO*, const char*)':
/home/psergey/dev-git/mysql-5.6-rocksdb-fixcompile/client/mysqlbinlog.cc:2409:31: error: format not a string literal and no format arguments [-Werror=format-security]
   sprintf(cur_logname, logname);
                               ^
cc1plus: all warnings being treated as errors
make[2]: *** [client/CMakeFiles/mysqlbinlog.dir/mysqlbinlog.cc.o] Error 1
make[2]: Target `client/CMakeFiles/mysqlbinlog.dir/build' not remade because of errors.
```

**Comment by spetrunia** [comment]
Fix pushed
